### PR TITLE
Upgrade to PHPUnit 7

### PR DESCRIPTION
**Pull request by enumag**

### CODE REVIEW

**Comment by enumag** [comment]
@gavinlove This is ready now in my opinion. Sadly it doesn't seem possible to make it work with both PHPUnit 6 and 7.

**Comment by enumag** [comment]
ping @gavinlove

**Comment by ruudk** [comment]
Any news on this? 🙏

**Comment by alister** [comment]
Over the weekend I did try the fork that @enumag has created, and it does work for me (on PHPUnit 7.1.5). I'd also agree that supporting PHPunit 6 & 7 together would probably be too much work. 

However, even with full PHPunit7 support, trying various combinations of my test suites (only quick tests & everything with, and without coverage) only produced a tiny decrease in time or memory being used on PHP 7.2.  Of the order of 2 seconds out of a 120 second runtime, and a few megabytes out of 1000mb for a full coverage run. In my mind, that makes this project effectively **obsolete** for a modern PHP version.  Far greater gains can be gotten with avoiding database interactions, or not spinning up a kernel & DI-container for a test that does not need one (I'm down 15x that much just by doing that this morning).

So, I would suggest **not** supporting PHPunit v7, *and also* not even suggesting the listener's use on PHP v7.1+ - in good part by simply not testing on PHP 7 or deliberately not even allowing it to run on at least PHP 7.2.

**Pull request merged**
